name: Add merge comment

on:
  pull_request_target:
    types: [closed]

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  add-merge-comment:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate Comment
        id: generate_comment
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pull_request = context.payload.pull_request;
            const author = pull_request.user.login;
            const issue_number = pull_request.number;
            const body = `Thanks @${author} üèÜ`;
            console.log(`Generated comment: ${body}`);
            core.setOutput('body', body);

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: ${{ steps.generate_comment.outputs.body }}
          reactions: rocket
